export default {
	GET_STOCK_PRICE_START: 'GET_STOCK_PRICE_START',
	EXPAND_STOCK_PRICE: 'EXPAND_STOCK_PRICE',
	GET_STOCK_PRICE_SUCCESS: 'GET_STOCK_PRICE_SUCCESS',
	GET_STOCK_PRICE_ERROR: 'GET_STOCK_PRICE_ERROR',
	GET_EARNINGS_START: 'GET_EARNINGS_START',
	GET_EARNINGS_SUCCESS: 'GET_EARNINGS_SUCCESS',
	GET_EARNINGS_ERROR: 'GET_EARNINGS_ERROR',
}
